# Generated by Django 5.0.2 on 2024-02-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('title', models.CharField(max_length=20)),
                ('year_of_publishing', models.DateField()),
                ('Book_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=15)),
                ('number_of_pages', models.IntegerField()),
                ('book_price', models.IntegerField()),
            ],
        ),
    ]
